name: Apollo-Example
main: com.lunarclient.apollo.example.ApolloExamplePlugin
version: 0.1.0-SNAPSHOT
author: Moonsworth
depend: [Apollo-Bukkit]

commands:
    beam:
        description: "Beams!"
    border:
        description: "Borders!"
    coloredfire:
        description: "Colored Fires!"
    cooldown:
        description: "Cooldowns!"
    hologram:
        description: "Holograms!"
    limb:
        description: "Limb!"
    misc:
        description: "Misc!"
    modsettings:
        description: "ModSettings!"
    nametag:
        description: "Nametags!"
    notification:
        description: "Notifications!"
    tntcountdown:
        description: "TNT Countdown!"
    transfer:
        description: "Transfer!"
