modules:
  LegacyCombatModule:
    enabled: true
    disableEntityCramming: true
    disableEnderpearlCooldown: true
    disableSwingSounds: true
    disableSweep: true
    legacyCrits: true
    legacyAttackSpeed: true
    armorDurability: true
    projectileDamage: true
    armorDurabilityReduction: 1
    noDamageTicks: 19
    attackSpeed: 16
    projectileRandomnessValue: 0.1
    regenInterval: 3990
    regenHealAmount: 1
    regenExhaustionHealAmount: 3
  StaffModModule:
    enabled: true
    xray: "apollo.staffmods.xray"
