metadata.format.version = "1.1"

[versions]
artifactregistry = "2.2.0"
checkstyle = "10.9.3"
configurate = "4.1.2"
geantyref = "1.3.11"
jetbrains = "24.0.1"
lombok = "1.18.26"
protobuf = "3.21.4"
protobufPlugin = "0.9.2"

[libraries]
geantyref = { module = "io.leangen.geantyref:geantyref", version.ref = "geantyref" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

protobuf = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
configurate-core = { module = "org.spongepowered:configurate-core", version.ref = "configurate" }
configurate-hocon = { module = "org.spongepowered:configurate-hocon", version.ref = "configurate" }

stylecheck = "ca.stellardrift:stylecheck:0.2.0"

artifactregistry = { module = "gradle.plugin.com.google.cloud.artifactregistry:artifactregistry-gradle-plugin", version.ref = "artifactregistry" }
checkstyle = { module = "com.puppycrawl.tools:checkstyle", version.ref = "checkstyle" }

[plugins]
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }
