metadata.format.version = "1.1"

[versions]
artifactregistry = "2.2.0"
checkstyle = "10.9.3"
configurate = "4.1.2"
geantyref = "1.3.11"
ignite = "0.8.1"
jetbrains = "24.0.1"
lombok = "1.18.26"
mixin = "0.8.5"
paperweight = "1.5.4"
protobuf = "3.21.4"
protobufPlugin = "0.9.2"
shadow = "7.1.2"

[libraries]
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

# api
geantyref = { module = "io.leangen.geantyref:geantyref", version.ref = "geantyref" }

# common
protobuf = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
configurate-core = { module = "org.spongepowered:configurate-core", version.ref = "configurate" }
configurate-hocon = { module = "org.spongepowered:configurate-hocon", version.ref = "configurate" }

# bukkit platform
ignite = { module = "space.vectrix.ignite:ignite-api", version.ref = "ignite" }
mixin = { module = "org.spongepowered:mixin", version.ref = "mixin" }

# build
artifactregistry = { module = "gradle.plugin.com.google.cloud.artifactregistry:artifactregistry-gradle-plugin", version.ref = "artifactregistry" }
checkstyle = { module = "com.puppycrawl.tools:checkstyle", version.ref = "checkstyle" }
paperweight = { module = "io.papermc.paperweight.userdev:io.papermc.paperweight.userdev.gradle.plugin", version.ref = "paperweight" }
shadow = { module = "gradle.plugin.com.github.johnrengelman:shadow", version.ref = "shadow" }

stylecheck = "ca.stellardrift:stylecheck:0.2.0"

[plugins]
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }
