name: Deploy
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    name: Deploy

    steps:
      - name: Checkout from GitHub
        uses: actions/checkout@master

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ARTIFACTS_ROLE_ARN }}
          aws-region: us-east-2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 16
     
      - name: Publish
        run: ./gradlew publish
